### ISSUE TITLE
Gulp build fails when folders are passed

### ISSUE THREAD

**Issue by DHainzl** [oricalvo/systemjs-cachebuster#4]
I use the following code in my `gulpfile.js`:

```
    return gulp
            .src(DEST_DIR + '/**')
            .pipe(cacheBuster.full())
```

DEST_DIR contains a hierarchy of files and (sub-)folders. 

When I now try to run my build I get the following error:

```
crypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at SystemJSCacheBuster._processFile (/Users/david/Documents/Repos/ChannelManager/app-ng/node_modules/systemjs-cachebuster/src/system.cachebuster.gulp.js:36:42)
    at Transform.FileHashTransform.write (/Users/david/Documents/Repos/ChannelManager/app-ng/node_modules/systemjs-cachebuster/src/system.cachebuster.gulp.js:63:16)
    at write (/Users/david/Documents/Repos/ChannelManager/app-ng/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/david/Documents/Repos/ChannelManager/app-ng/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/david/Documents/Repos/ChannelManager/app-ng/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at emitReadable_ (/Users/david/Documents/Repos/ChannelManager/app-ng/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/david/Documents/Repos/ChannelManager/app-ng/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
```

This happens because the _transform() function is also called for folders and not only for files. the `_content` of a folder is `null` and crypto.js fails when you pass `null`.

**Comment by DHainzl** [comment]
This is my first time contributing to a different repository so if I make any mistakes feel free to correct me :)

The pull request above should fix this behaviour. I also have two more branches with features; If you want to include them all I've already combined them to a separate branch - issues and PRs will follow up shortly.
https://github.com/DHainzl/systemjs-cachebuster/tree/total-code
